services:
  pids:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}-pids
    networks:
      - shared_network
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DOCKER_PORT: ${DOCKER_PORT:-5432}
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./:/home/pids
      - ${ARTIFACTS_DIR:-/home/artifacts}:/home/artifacts
      # - /path/to/raw/data:/data
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  shared_network:
    external:
      name: shared_network
